---
# tasks file for create project
- name: Create a 
  openshift_raw:
    api_version: v1
    verify_ssl: no
    host: "{{ api_url }}"
    username: "{{ oc_username }}"
    password: "{{ oc_password }}"
    kind: Project
    name: "{{ ocproject }}"
    state: present
    validate_certs: no