---
# tasks file for create project
- name: Create a k8
  k8s:
    api_version: v1
    state: present
    name: "{{ocproject}}"
    host: "{{api_url}}"
    username: "{{oc_username}}"
    password: "{{oc_password}}"
    kind: Namespace
    validate_certs: no