---
# tasks file for create project
- name: Create a Demo Project in RHOCP
  openshift_raw:
    api_version: v1
    host: "{{ api_url }}"
    username: "{{ oc_username }}"
    password: "{{ oc_password }}"
    kind: Project
    name: "{{ ocproject }}"
    ca_cert: "{{ ca_path }}"
    state: present