---
# tasks file for create project

- name: Create a project
  openshift_raw:
    state: present
    host: "{{api_url}}"
    username: "{{oc_username}}"
    password: "{{oc_password}}"
    definition:
      api_version: v1
      verify_ssl: no
      kind: Namespace
      metadata:
        name: "{{ocproject}}"