---
# tasks file for create project

- name: Create a project
  openshift_raw:
    api_version: v1
    verify_ssl: no
    host: https://openshift.dv.seccloud.internal
    username: "{{ oc_username }}"
    password: "{{ oc_password }}"
    kind: Project
    name: "{{ ocproject }}"
    state: present