---
# tasks file for create project

- name: Create a project
  openshift_raw:
    api_version: v1
    verify_ssl: no
    host: "openshift.dv.seccloud.internal:8443"
    username: "{{ oc_username }}"
    password: "{{ oc_password }}"
    kind: Project
    name: "{{ ocproject }}"
    state: present